In [0]:
import string 
import numpy as np
import pandas as pd
import re
from nltk.tokenize import TweetTokenizer
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences

In [17]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [18]:
cd /content/drive/My\ Drive/nlp 3

/content/drive/My Drive/nlp 3


In [19]:
data = pd.read_csv('train.txt', delimiter="\t",header=None,names=["meta", "uid", "senti"])
meta=data['meta']
uid=data['uid']
senti=data['senti']

X_train_arr=[]
Y_train_arr=[]
temp=""
for i,j,k in zip(meta,uid,senti):
    if i=='meta':
        
        if len(temp)!=0:
            X_train_arr.append(temp)
        Y_train_arr.append(k)
        temp=""
    else:
        try:
          if j!='O':
            i=re.sub(r'[\t\n]+','',i)
            temp=temp+i+" "
            temp.append(i)
        except:
            pass
X_train_arr.append(temp)
X_train_arr[:5]

['AdilNisarButt pakistan ka ghra tauq he Pakistan Israel ko tasleem nahein kerta Isko Palestine kehta he OCCUPIED PALESTINE ',
 'Madarchod mulle ye mathura me Nahi dikha tha jab mullo ne Hindu ko iss liye mara ki vo lasse ki paise mag liye the https t co oxf8tr3bly ',
 'narendramodi Manya Pradhan Mantri mahoday Shriman Narendra Modi ji Pradhanmantri banne par Hardik Badhai tahe Dil https t co pRnoMsKkn1 ',
 'Atheist Krishna Jcb full trend me chal rahi aa ',
 'AbhisharSharma RavishKumarBlog Loksabha me janta sirf modi ko vote de rahi thi na ki kisi MP or BJP ko without m https t co sHtBWCB7FM ']

In [20]:
data = pd.read_csv('test.txt', delimiter="\t",header=None,names=["meta", "uid", "senti"])
meta=data['meta']
uid=data['uid']
senti=data['senti']
X_test_arr=[]
Y_test_arr=[]
temp=""
for i,j,k in zip(meta,uid,senti):
    if i=='meta':
        
        if len(temp)!=0:
            X_test_arr.append(temp)
        Y_test_arr.append(k)
        temp=""
    else:
        try:
          if j!='O':
            i=re.sub(r'[\t\n]+','',i)
            temp=temp+i+" "
            temp.append(i)
        except:
            pass
X_test_arr.append(temp)
X_test_arr

['RT UAAPconfessions Love looks good on Maddie Ako lang ba yung sobrang masaya kasi may zolo sya Before with the past Z medyo lowkey s ',
 'Ye Ye ye We gonna start another June on a sour note Uhhhh yes no yes no yes ',
 'zWffFY9JGklElA1 Min Of Lyching thakurdadu089 manakgupta OfficeOfKNath Mein kahna nae chahta qki mere Yaha btay https tco JWSdvvomt8 ',
 'Caring Bohot Jyada Caring Courier wale bsdk ke sign bhi khud hi krlete h mera ',
 'AliHZaidiPTI SarfarazA What nonesense Kabhi baymani per bani team kamiyab nahi ho sakti Jo log apnay liy https t co al1WFCUTYy ',
 'imVkohli Best of luck imVkohli sir World Cup ke liye bhot bhot subhkamnaye ',
 'Yes Great dialogues in that one Also Chupke Chupke over Chhaddabeshi All except R G V Ke Sholay https t co MHCBkX0SnG ',
 'mangeshkarlata Desh bhakti baat wahi samajh sakte hai jo khud deshbhakt Wo log to sirf Bharat tere tukde hong https t co rMdZSiwSGT ',
 'Pakistani team ne effort ki Aagey Allah ki marziiiiiiiiiiiii PAKvWI WIvPAK CWC19 WeHave

In [21]:
X_train_arr[:5]

['AdilNisarButt pakistan ka ghra tauq he Pakistan Israel ko tasleem nahein kerta Isko Palestine kehta he OCCUPIED PALESTINE ',
 'Madarchod mulle ye mathura me Nahi dikha tha jab mullo ne Hindu ko iss liye mara ki vo lasse ki paise mag liye the https t co oxf8tr3bly ',
 'narendramodi Manya Pradhan Mantri mahoday Shriman Narendra Modi ji Pradhanmantri banne par Hardik Badhai tahe Dil https t co pRnoMsKkn1 ',
 'Atheist Krishna Jcb full trend me chal rahi aa ',
 'AbhisharSharma RavishKumarBlog Loksabha me janta sirf modi ko vote de rahi thi na ki kisi MP or BJP ko without m https t co sHtBWCB7FM ']

In [22]:
Y_train_arr[:5]

['negative', 'negative', 'positive', 'positive', 'positive']

In [23]:
X_test_arr[:5]

['RT UAAPconfessions Love looks good on Maddie Ako lang ba yung sobrang masaya kasi may zolo sya Before with the past Z medyo lowkey s ',
 'Ye Ye ye We gonna start another June on a sour note Uhhhh yes no yes no yes ',
 'zWffFY9JGklElA1 Min Of Lyching thakurdadu089 manakgupta OfficeOfKNath Mein kahna nae chahta qki mere Yaha btay https tco JWSdvvomt8 ',
 'Caring Bohot Jyada Caring Courier wale bsdk ke sign bhi khud hi krlete h mera ',
 'AliHZaidiPTI SarfarazA What nonesense Kabhi baymani per bani team kamiyab nahi ho sakti Jo log apnay liy https t co al1WFCUTYy ']

In [24]:
Y_test_arr[:5]

['neutral', 'neutral', 'neutral', 'negative', 'positive']

In [25]:
print(len(X_train_arr), len(Y_train_arr), len(X_test_arr), len(Y_test_arr))

13524 13524 1869 1869


In [0]:
def clean_tweets(text, tknzr):
  tweet_tokens = tknzr.tokenize(text)
  tweet = ""
  for j in tweet_tokens:
    if(j not in string.punctuation and j not in ['…']):
      tweet += (j.lower()+" ")
  return tweet.strip()

In [0]:
tknzr = TweetTokenizer(strip_handles=True, reduce_len=True)

In [0]:
X_train_cleaned = list()
for i in range(len(X_train_arr)):
  X_train_cleaned.append(clean_tweets(X_train_arr[i],tknzr))

In [29]:
X_train_cleaned[:5]

['adilnisarbutt pakistan ka ghra tauq he pakistan israel ko tasleem nahein kerta isko palestine kehta he occupied palestine',
 'madarchod mulle ye mathura me nahi dikha tha jab mullo ne hindu ko iss liye mara ki vo lasse ki paise mag liye the https t co oxf 8tr3bly',
 'narendramodi manya pradhan mantri mahoday shriman narendra modi ji pradhanmantri banne par hardik badhai tahe dil https t co prnomskkn 1',
 'atheist krishna jcb full trend me chal rahi aa',
 'abhisharsharma ravishkumarblog loksabha me janta sirf modi ko vote de rahi thi na ki kisi mp or bjp ko without m https t co shtbwcb 7fm']

In [0]:
X_test_cleaned = list()
for i in range(len(X_test_arr)):
  X_test_cleaned.append(clean_tweets(X_test_arr[i], tknzr))

In [31]:
X_test_cleaned[:5]

['rt uaapconfessions love looks good on maddie ako lang ba yung sobrang masaya kasi may zolo sya before with the past z medyo lowkey s',
 'ye ye ye we gonna start another june on a sour note uhhh yes no yes no yes',
 'zwfffy 9jgklela1 min of lyching thakurdadu 089 manakgupta officeofknath mein kahna nae chahta qki mere yaha btay https tco jwsdvvomt 8',
 'caring bohot jyada caring courier wale bsdk ke sign bhi khud hi krlete h mera',
 'alihzaidipti sarfaraza what nonesense kabhi baymani per bani team kamiyab nahi ho sakti jo log apnay liy https t co al1wfcutyy']

In [0]:
tk = Tokenizer(num_words=None, char_level=True, oov_token='UNK')
tk.fit_on_texts(X_train_cleaned)

In [0]:
X_train_seq = tk.texts_to_sequences(X_train_cleaned)
X_test_seq = tk.texts_to_sequences(X_test_cleaned)

In [0]:
max_tweet_len = 200

In [0]:
X_train = pad_sequences(X_train_seq, maxlen=max_tweet_len, padding='post')
X_test = pad_sequences(X_test_seq, maxlen=max_tweet_len, padding='post')

In [36]:
X_train = np.array(X_train, dtype='float32')
X_test = np.array(X_test, dtype='float32')
X_train

array([[ 3., 15.,  4., ...,  0.,  0.,  0.],
       [13.,  3., 15., ...,  0.,  0.,  0.],
       [10.,  3.,  9., ...,  0.,  0.,  0.],
       ...,
       [ 3., 13., 22., ...,  0.,  0.,  0.],
       [11., 16., 10., ...,  0.,  0.,  0.],
       [12., 16., 10., ...,  0.,  0.,  0.]], dtype=float32)

In [0]:
from keras.utils import to_categorical
def sentimentToIntegers(arr):
  integerSentiments = list()
  for i in arr:
    if(i == "positive"):
      integerSentiments.append(0)
    elif(i == "negative"):
      integerSentiments.append(1)
    else:
      integerSentiments.append(2)
  
  integerSentiments = np.array(integerSentiments,dtype='float32')
  categoricalSentiments = to_categorical(integerSentiments)

  return categoricalSentiments

In [38]:
Y_train = sentimentToIntegers(Y_train_arr)
Y_test = sentimentToIntegers(Y_test_arr)
Y_test

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       ...,
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.]], dtype=float32)

In [39]:
X_train.shape, Y_train.shape, X_test.shape, Y_test.shape

((13524, 200), (13524, 3), (1869, 200), (1869, 3))

In [40]:
vocab_size = len(tk.word_index)
vocab_size

94

In [0]:
embedding_weights = []
# embedding_weights.append(np.zeros(vocab_size))

for char, i in tk.word_index.items():
    onehot = np.zeros(vocab_size)
    onehot[i - 1] = 1
    embedding_weights.append(onehot)

embedding_weights = np.array(embedding_weights)

In [0]:
from keras.models import Sequential
from keras.layers import Dense, Input, Dropout, MaxPooling1D, Conv1D, GlobalMaxPool1D, Embedding, Flatten
from keras.layers import LSTM, Lambda, concatenate, TimeDistributed, Bidirectional

In [44]:
num_of_sentiments = 3
embedding_size = vocab_size
conv_layers = [[256, 3, 3],
               [256, 3, -1],
                              [256, 3, -1],

               [256, 3, 3]]


batch_size = 32

model = Sequential()

# inputs = (None, max_tweet_len) = (None, 50)

model.add(Embedding(input_dim=vocab_size, output_dim=embedding_size, input_length = max_tweet_len, weights=[embedding_weights]))

# shape = (None, max_tweet_len, embedding_size) = (None, 50, 500)

for filter_num, filter_size, pooling_size in conv_layers:
    model.add(Conv1D(filter_num, filter_size, activation='relu'))
    if pooling_size != -1:
        model.add(MaxPooling1D(pool_size=pooling_size))

model.add(Flatten())

model.add(Dense(units=512, activation='relu'))
model.add(Dropout(0.2))

model.add(Dense(units=512, activation='relu'))
model.add(Dropout(0.2))


model.add(Dense(units=num_of_sentiments, activation='softmax'))

model.summary()












Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 200, 94)           8836      
_________________________________________________________________
conv1d_1 (Conv1D)            (None, 198, 256)          72448     
_________________________________________________________________
max_pooling1d_1 (MaxPooling1 (None, 66, 256)           0         
_________________________________________________________________
conv1d_2 (Conv1D)            (None, 64, 256)           196864    
_________________________________________________________________
conv1d_3 (Conv1D)            (None, 62, 256)           196864    
_________________________________________________________________
conv1d_4 (Conv1D)            (None, 60, 256)           19686

In [0]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [0]:
model.fit(X_train, Y_train, batch_size=32, epochs=50, validation_data=(X_test, Y_test), verbose=1)

Train on 13524 samples, validate on 1869 samples
Epoch 1/50
13524/13524 [==============================] - 13s 975us/step - loss: 1.0257 - acc: 0.4457 - val_loss: 1.0784 - val_acc: 0.4077
Epoch 2/50
13524/13524 [==============================] - 12s 875us/step - loss: 0.8946 - acc: 0.5617 - val_loss: 1.0324 - val_acc: 0.5094
Epoch 3/50
13524/13524 [==============================] - 12s 868us/step - loss: 0.8291 - acc: 0.6121 - val_loss: 0.9829 - val_acc: 0.5340
Epoch 4/50
13524/13524 [==============================] - 12s 873us/step - loss: 0.7614 - acc: 0.6604 - val_loss: 1.0961 - val_acc: 0.5045
Epoch 5/50
13524/13524 [==============================] - 12s 873us/step - loss: 0.6911 - acc: 0.6999 - val_loss: 1.1912 - val_acc: 0.5340
Epoch 6/50
13524/13524 [==============================] - 12s 862us/step - loss: 0.6049 - acc: 0.7499 - val_loss: 1.1927 - val_acc: 0.5163
Epoch 7/50
13524/13524 [==============================] - 11s 837us/step - loss: 0.5119 - acc: 0.7924 - val_loss: 1.1

In [0]:
model.save("A3.h5")

In [45]:
from keras.models import load_model
model=load_model("A3.h5")



Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where




In [0]:
from sklearn.metrics import confusion_matrix, f1_score, precision_score, recall_score,accuracy_score

In [47]:
f1score = []
recalls = []
precisions = []
acc=[]

predict = (np.array(model.predict(X_test))).round() 
targ = Y_test
f1 = f1_score(targ, predict,average=None)
recall = recall_score(targ, predict,average=None)
precision = precision_score(targ, predict,average=None)
accuracy=accuracy_score(targ, predict)
f1score.append(f1)
recalls.append(recall)
precisions.append(precision)
acc.append(accuracy)
print(predict)

[[0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 ...
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]


In [48]:
print("Accuracy: %f \nf1_Positive: %f \nf1_Negetive: %f \nf1_Neutral: %f \nprecision_Positive: %f \nprecision_Negetive: %f \nprecision_Neutral: %f \nrecall_Positive %f \nrecall_Negetive %f \nrecall_Neutral %f" %(accuracy,f1[0], f1[1], f1[2], precision[0], precision[1], precision[2], recall[0], recall[1], recall[2]))

Accuracy: 0.521669 
f1_Positive: 0.546966 
f1_Negetive: 0.534653 
f1_Neutral: 0.503684 
precision_Positive: 0.529791 
precision_Negetive: 0.566038 
precision_Neutral: 0.508796 
recall_Positive 0.565292 
recall_Negetive 0.506567 
recall_Neutral 0.498674
